language: julia
julia:
  - 0.5
  - nightly
notifications:
  email: false
before_install:
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - julia -e 'Pkg.add("Conda"); using Conda; Conda.add("yt")'
  - export CONDA_PYTHON=`julia -e 'import Conda; print(Conda.PREFIX)'`
  - export PATH=$CONDA_PYTHON/bin:$PATH
  - export LD_LIBRARY_PATH=$CONDA_PYTHON/lib
after_success:
  - julia -e 'cd(Pkg.dir("YT")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
